### ISSUE TITLE
No access to R Shiny repo

### ISSUE THREAD

**Issue by DagHjermann** [ijlyttle/reactivity-three-ways-quarto#3]
Thanks a lot for this breakdown / comparison! I have just hightlighted this in my workplace's forum for data science.

I just want to make you aware that I cannot access the R Shiny repo. Probably the repo is not set to public - at least I get a 404 error for https://github.com/ijlyttle/reactivity-demo-shiny .

All the best,
Dag

**Comment by ijlyttle** [comment]
Hi Dag,

Thanks so much for the kind words - and also for letting me know the repo was private 🤦. It is now public!

Thanks,

Ian
